#!/usr/bin/env python3
"""
Export YouTube cookies from Firefox to cookies.txt format
Run this script on the machine where Firefox is installed and logged into YouTube
"""

import sqlite3
import os
import sys
from pathlib import Path
import shutil

def find_firefox_profile():
    """Find the default Firefox profile directory"""
    home = Path.home()

    # Linux Firefox profile location
    firefox_dir = home / ".mozilla" / "firefox"

    if not firefox_dir.exists():
        print(f"❌ Firefox directory not found at {firefox_dir}")
        return None

    # Find the default profile (usually ends with .default-release)
    profiles = list(firefox_dir.glob("*.default*"))
    if not profiles:
        print(f"❌ No Firefox profiles found in {firefox_dir}")
        return None

    # Use the first profile found (usually the default one)
    profile = profiles[0]
    print(f"✓ Found Firefox profile: {profile}")
    return profile

def export_cookies(profile_path, output_file="cookies.txt"):
    """Export YouTube cookies from Firefox SQLite database"""

    cookies_db = profile_path / "cookies.sqlite"

    if not cookies_db.exists():
        print(f"❌ Cookies database not found: {cookies_db}")
        return False

    # Make a temporary copy (Firefox locks the original)
    temp_db = "/tmp/cookies_temp.sqlite"
    try:
        shutil.copy2(cookies_db, temp_db)
    except Exception as e:
        print(f"❌ Failed to copy cookies database: {e}")
        print("Make sure Firefox is closed and try again")
        return False

    try:
        # Connect to the temporary database
        conn = sqlite3.connect(temp_db)
        cursor = conn.cursor()

        # Query YouTube cookies
        cursor.execute("""
            SELECT host, name, value, path, expiry, isSecure
            FROM moz_cookies
            WHERE host LIKE '%youtube.com%' OR host LIKE '%google.com%'
            ORDER BY host, name
        """)

        cookies = cursor.fetchall()
        conn.close()

        if not cookies:
            print("❌ No YouTube cookies found. Make sure you're logged into YouTube in Firefox!")
            return False

        # Write in Netscape cookie format
        with open(output_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by export_firefox_cookies.py\n\n")

            for host, name, value, path, expiry, isSecure in cookies:
                # Format: domain  flag  path  secure  expiration  name  value
                domain = host if host.startswith('.') else '.' + host
                flag = "TRUE"
                secure = "TRUE" if isSecure else "FALSE"
                expiration = str(expiry) if expiry else "0"

                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

        print(f"✓ Exported {len(cookies)} cookies to {output_file}")

        # Check for important auth cookies
        cookie_names = [name for _, name, _, _, _, _ in cookies]
        important_cookies = ['SAPISID', 'SSID', 'APISID', 'HSID', 'SID']
        found_auth = [c for c in important_cookies if c in cookie_names]

        if found_auth:
            print(f"✓ Found authentication cookies: {', '.join(found_auth)}")
            print("✓ These cookies should work for YouTube downloads!")
        else:
            print("⚠️  Warning: No authentication cookies found!")
            print("   Make sure you're logged into YouTube in Firefox")

        return True

    except Exception as e:
        print(f"❌ Error reading cookies: {e}")
        return False
    finally:
        # Clean up temp file
        if os.path.exists(temp_db):
            os.remove(temp_db)

def main():
    print("=" * 60)
    print("Firefox YouTube Cookie Exporter")
    print("=" * 60)

    # Find Firefox profile
    profile = find_firefox_profile()
    if not profile:
        print("\n💡 Tip: Make sure Firefox is installed and you've used it at least once")
        sys.exit(1)

    # Export cookies
    output_file = "cookies.txt"
    print(f"\nExporting cookies to: {os.path.abspath(output_file)}")

    if export_cookies(profile, output_file):
        print("\n" + "=" * 60)
        print("✓ SUCCESS!")
        print("=" * 60)
        print(f"\nCookies saved to: {os.path.abspath(output_file)}")
        print("\nNext steps:")
        print("1. The cookies.txt file is ready to use")
        print("2. Restart your Voice2Note app if it's running")
        print("3. Try downloading a YouTube video")
        return 0
    else:
        print("\n" + "=" * 60)
        print("❌ FAILED")
        print("=" * 60)
        print("\nTroubleshooting:")
        print("1. Close Firefox completely and try again")
        print("2. Make sure you're logged into YouTube in Firefox")
        print("3. Try visiting youtube.com in Firefox first")
        return 1

if __name__ == "__main__":
    sys.exit(main())
